/** @deprecated Consult persistence contracts are owned by contribbot-core. */
export {
  authorizationSchema,
  bindingSchema,
  categorySchema,
  databaseSchema,
  decisionSchema,
  digest,
  digestSchema,
  discussionSchema,
  grantSchema,
  grantSpecSchema,
  idSchema,
  manifestEntrySchema,
  materialSchema,
  MAX_PACKET_BYTES,
  occupiesLocal,
  packetInputSchema,
  packetSchema,
  processSchema,
  purposeSchema,
  reconcileInputSchema,
  reconciliationReportSchema,
  reconciliationSchema,
  releaseObservationSchema,
  resultSchema,
  runtimeInputSchema,
  runtimeSchema,
  scopeSchema,
  synthesisSchema,
  textSchema,
  todoSnapshotSchema,
  turnSchema,
} from 'contribbot-core'
export type {
  Authorization,
  Binding,
  Database,
  Decision,
  Discussion,
  Grant,
  GrantSpec,
  Packet,
  PacketInput,
  ReconcileInput,
  RuntimeInput,
  Scope,
  TodoSnapshot,
  Turn,
  TurnResult,
} from 'contribbot-core'
